import { Inter } from "next/font/google";
import "../../globals.css";
import vazirFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";
import Providers from "../../Providers";
import Header from "../../Header";
import Footer from "../../Footer";
import Sidbar from "./Sidbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "پروفایل ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
        <Providers>
          <Toaster
            containerStyle={{
              fontSize: "1.2rem",
            }}
          />
          <div className="flex flex-col h-screen">
            <div className="grid grid-cols-1 lg:grid-cols-5">
              <Sidbar />
              <main className="lg:col-span-4">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
