import { Inter } from "next/font/google";
import "../../globals.css";
import vazirFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";
import Providers from "../../Providers";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "سایت فروش",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
        <Providers>
          <Toaster
            containerStyle={{
              fontSize: "1.2rem",
            }}
          />
          <div className="h-screen">
            <div className="lg:container mx-auto grid grid-cols-1 lg:grid-cols-5 gap-4 px-6 py-6">
              <div className="relative ">
                <Sidebar />
              </div>
              <main className="lg:col-span-4 p-4 border rounded-xl shadow">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
export default RootLayout;
